### ISSUE TITLE
[Error] Cannot find module 'node:path'

### ISSUE THREAD

**Issue by Kush-Dhingra** [Bashamega/TrendTrack#18]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

``` javascript
Error: Cannot find module 'node:path'
Require stack:
- /mnt/c/Users/kushd/AppData/Roaming/nvm/v22.4.1/node_modules/npm/lib/cli.js
- /mnt/c/Users/kushd/AppData/Roaming/nvm/v22.4.1/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/mnt/c/Users/kushd/AppData/Roaming/nvm/v22.4.1/node_modules/npm/lib/cli.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/kushd/AppData/Roaming/nvm/v22.4.1/node_modules/npm/lib/cli.js',
    '/mnt/c/Users/kushd/AppData/Roaming/nvm/v22.4.1/node_modules/npm/bin/npm-cli.js'
  ]
}
```

### Steps to Reproduce

Run code

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
Do you have node and npm properly  configured on your system?

**Comment by Kush-Dhingra** [comment]
> Do you have node and npm properly configured on your system?
> 
> NOTE: It needs Node 16+ to run

**Comment by Bashamega** [comment]
> I am an idiot

No, you are not
